'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { HomeProvider } from '@/context/HomeContext'


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <HomeProvider>
          {children}
        </HomeProvider>
        </body>
    </html>
  );
}
