/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QkTgJS854CB
 */
import { CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Carousal() {
  return (
    (<div
      className="w-full max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
      <Carousel
        className="w-full max-w-3xl mx-auto p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <CarouselContent className="grid grid-cols-3 gap-4">
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardContent className="flex flex-col gap-2">
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Name</span>
                    <span>John Doe</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Email</span>
                    <span>johndoe@example.com</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Role</span>
                    <span>Admin</span>
                  </div>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardContent className="flex flex-col gap-2">
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Name</span>
                    <span>Jane Smith</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Email</span>
                    <span>janesmith@example.com</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Role</span>
                    <span>User</span>
                  </div>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardContent className="flex flex-col gap-2">
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Name</span>
                    <span>Bob Johnson</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Email</span>
                    <span>bobjohnson@example.com</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Role</span>
                    <span>Admin</span>
                  </div>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="p-1">
              <Card>
                <CardContent className="flex flex-col gap-2">
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Name</span>
                    <span>Alice Williams</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Email</span>
                    <span>alicewilliams@example.com</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="font-semibold">Role</span>
                    <span>User</span>
                  </div>
                </CardContent>
              </Card>
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
      </Carousel>
    </div>)
  );
}
