/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RVMKi8fANFb
 */
"use client";

import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { useContext, useEffect, useState } from "react"
import { useRouter } from "next/navigation";
import HomeContext from "@/context/HomeContext";



export function Feedback1() {

  const { ridedetails, setridedetails } = useContext(HomeContext);
  const tkn=localStorage.getItem("authToken");


console.log(ridedetails);
  const [credentials, setcredentials] = useState({});
  const onchange = (e) => {
    setcredentials({ ...credentials, [e.target.name]: e.target.value });
  };


  const router = useRouter()
  const eventHandler = async () => {
    
    if(Object.keys(credentials).length===1){

      const body = {
        id: ridedetails._id,
        feedBack: credentials.feedback,
      };
      const response = await fetch("http://localhost:3001/rideCompletes", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "token": tkn,

      },
      body: JSON.stringify(body),
    });
    const data = await response.json();
    console.log(data);
    if (!data.success) {
      alert("Ride is not cancelled");
    }
    else {
      console.log("ride completed")
      setridedetails()
      router.push('http://localhost:3000/BookRide', { scroll: false })
    }
  }
  else{
    alert("Fill filled properly")
  }
    
  }
  useEffect(()=>{
    console.log(credentials)
    },[credentials])


  return (
    (<div className="w-full max-w-md mx-auto py-12">
      <Card>
        <CardHeader>
          <CardTitle>Feedback Form</CardTitle>
          <CardDescription>We value your feedback. Please let us know what you think.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="feedback">Your Feedback</Label>
              <Textarea
                className="min-h-[100px]"
                id="feedback"
                placeholder="Enter your feedback here" 
                name="feedback" value={credentials.feedback} onChange={onchange}
                
                />
            </div>
            <Button onClick={eventHandler}>Submit Feedback</Button>
          </div>
        </CardContent>
      </Card>
    </div>)
  );
}
