/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cH5sYU8sQXs
 */
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogHeader, DialogFooter, DialogContent, Dialog } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"

export function Feedback() {
  return (
    (<Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Give Feedback</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Feedback</DialogTitle>
          <DialogDescription>We value your feedback. Please share your experience with us.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="feedback">Your Feedback</Label>
            <Textarea
              className="min-h-[100px]"
              id="feedback"
              placeholder="Write your feedback here..." />
          </div>
          <div className="space-y-2">
            <Label htmlFor="rating">Rating</Label>
            <RadioGroup className="flex items-center gap-2" defaultValue="3" id="rating">
              <RadioGroupItem value="1">1</RadioGroupItem>
              <RadioGroupItem value="2">2</RadioGroupItem>
              <RadioGroupItem value="3">3</RadioGroupItem>
              <RadioGroupItem value="4">4</RadioGroupItem>
              <RadioGroupItem value="5">5</RadioGroupItem>
            </RadioGroup>
          </div>
        </div>
        <DialogFooter>
          <Button type="submit">Submit</Button>
          <div>
            <Button variant="outline">Close</Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>)
  );
}
