/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mOYLOLa2sqi
 */
"use client"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { useContext, useEffect, useState } from "react"
import HomeContext from '@/context/HomeContext';
import { useRouter } from 'next/navigation'



export function Login() {

  const { auth, setauth,isadmin,setisadmin } = useContext(HomeContext);
  useEffect(()=>{
    console.log(credentials)
    console.log(auth)
    console.log(isadmin)
    },[isadmin,auth])


  const [credentials, setcredentials] = useState({});
  const onchange = (e) => {
    setcredentials({ ...credentials, [e.target.name]: e.target.value });
  };

  const onSelect=(e)=>{
    console.log(e)
    setcredentials({ ...credentials, role: e.label });

  }

  const router = useRouter()
  const eventHandler = async () => {
    
    if(Object.keys(credentials).length===2){

      const body = {
        email: credentials.email,
        password: credentials.password,
      };
      const response = await fetch("http://localhost:3001/authloginUser", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });
    const data = await response.text();
    console.log(data);
    if (data == "user not found" || data == "password incorrect") {
      alert("No such user found");
    }
    else {
      const leyy = JSON.parse(data);
      console.log(leyy);
      localStorage.setItem("authToken", leyy.authToken);
      const athtkn=await localStorage.getItem("authToken")
       setauth(athtkn )
      console.log(localStorage.getItem("authToken"))
      console.log(auth)
      if(leyy.role==="admin"){
        
        localStorage.setItem("admin", true);
        setisadmin(true);
        console.log(isadmin)
      }
      router.push('http://localhost:3000', { scroll: false })
      // console.log(localStorage.getItem("authToken"));
      // router.push('http://localhost:3000/', { scroll: false })
    }
  }
  else{
    alert("Fill filled properly")
  }
    
  }
 

  return (
    (<Card className="mx-auto max-w-sm mt-[100px]">
      <CardHeader className="space-y-1">
        <CardTitle className="text-2xl font-bold">Login</CardTitle>
        <CardDescription>Enter your email below to login to your account</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
        <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input required type="email" name="email" value={credentials.email} onChange={onchange} />
          </div>
          <div className="space-y-2">
            <div className="flex items-center">
              <Label htmlFor="password">Password</Label>
              <Link className="ml-auto inline-block text-sm underline" href="#">
                Forgot your password?
              </Link>
            </div>
            <Input required type="password" name="password" value={credentials.password} onChange={onchange} />
          </div>
          <Button className="w-full" onClick={eventHandler}>
          Sign up
          </Button>
        </div>
        <div className="mt-4 text-center text-sm">
          Don't have an account?
          <Link className="underline" href="http://localhost:3000/CreateUser">
            Sign up
          </Link>
        </div>
      </CardContent>
    </Card>)
  );
}
