/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mOYLOLa2sqi
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import HomeContext from "@/context/HomeContext";
import { useContext } from "react";
import {Home} from "./Home"

export function Workspace() {
  return (
    <div >
      <Home/>
    </div>
  );
}
